### ISSUE TITLE
location is not updating

### ISSUE THREAD

**Issue by marsxul** [brendannee/whereisbart.com#2]
vehicle locations are not updating,   error given on webview

Uncaught TypeError: Cannot read property 'options' of undefined
    at e.bindPopup (https://unpkg.com/leaflet@0.6.0/dist/leaflet.js:7:22079)
    at https://whereisbart.com/js/main.js:135:22
    at Array.forEach (native)
    at https://whereisbart.com/js/main.js:110:30
    at Array.forEach (native)
    at https://whereisbart.com/js/main.js:105:19
    at Array.forEach (native)
    at Object.processBART [as success] (https://whereisbart.com/js/main.js:99:16)
    at c (https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js:3:7857)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js:3:8658)

**Comment by brendannee** [comment]
I upgraded leaflet library and fixed some things so this issue should be resolved.
